[build-system]
requires = ["setuptools >= 75.0"]
build-backend = "setuptools.build_meta"

[project]
name = "flux-schnell-edge-inference"
description = "An edge-maxxing model submission for the 4090 Flux contest"
requires-python = ">=3.10,<3.13"
version = "7"
dependencies = [
  "diffusers==0.31.0",
  "transformers==4.46.2",
  "accelerate==1.1.0",
  "omegaconf==2.3.0",
  "torch==2.5.1",
  "protobuf==5.28.3",
  "sentencepiece==0.2.0",
  "torchao==0.6.1",
  "edge-maxxing-pipelines @ git+https://github.com/womboai/edge-maxxing@7c760ac54f6052803dadb3ade8ebfc9679a94589#subdirectory=pipelines",
]

[tool.edge-maxxing]
models = ["black-forest-labs/FLUX.1-schnell"]

[project.scripts]
start_inference = "main:main"
